web/router.ex
defmodule Meep.Router do
  use Meep.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Meep do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/chats", ChatController, only: [:index]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Meep do
  #   pipe_through :api
  # end
end

lib/meep/endpoint.ex
defmodule Meep.Endpoint do
  use Phoenix.Endpoint, otp_app: :meep

  socket "/socket", Meep.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :meep, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_meep_key",
    signing_salt: "x8RvvZTB"

  plug Meep.Router
end

lib/meep/repo.ex
defmodule Meep.Repo do
  use Ecto.Repo, otp_app: :meep
end

web/controllers/chat_controller.ex
defmodule Meep.ChatController do
  use Meep.Web, :controller

  def index(conn, %{"chat" => %{"code" => code}}) do
    render(conn, "index.html", code: code)
  end

end

web/controllers/page_controller.ex
defmodule Meep.PageController do
  use Meep.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/views/chat_view.ex
defmodule Meep.ChatView do
  use Meep.Web, :view
end

web/views/error_view.ex
defmodule Meep.ErrorView do
  use Meep.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Meep.LayoutView do
  use Meep.Web, :view
end

web/views/page_view.ex
defmodule Meep.PageView do
  use Meep.Web, :view
end

web/templates/chat/index.html.eex
Code: <%= @code %>
<script type="text/javascript">
  window.code = "<%=@code%>";
</script>
<div id="elm-main"></div>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Meep!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<%= form_for @conn, chat_path(@conn, :index), [as: :chat, method: :get], fn f -> %>
  <%= text_input f, :code %>
  <%= submit "Start chat" %>
<% end %>